# Generated by Django 4.2 on 2024-09-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_photo',
            field=models.ImageField(default='default_photos/default_profile.png', upload_to='default_photos/'),
        ),
    ]
