# Generated by Django 4.2 on 2024-08-19 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('brief', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('status', models.CharField(choices=[('draft', 'Не проверено'), ('published', 'Проверено'), ('archived', 'Архив')], default='draft', max_length=10, verbose_name='Статус')),
                ('tags', models.ManyToManyField(blank=True, to='news.tag', verbose_name='Теги')),
            ],
        ),
    ]
