# Generated by Django 4.2 on 2024-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
