# Generated by Django 4.2 on 2024-11-13 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_news', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
    ]
