# Generated by Django 4.2 on 2024-11-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_comment_dislikes_news_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='dislikes',
        ),
    ]
